[project]
name = "repl-nix-winewise-2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "pinecone-client>=5.0.1",
    "plotly>=5.24.1",
    "python-dotenv>=1.0.1",
    "streamlit>=1.40.1",
]
